server:
  port: 80
  servlet:
    session:
      timeout: 300s

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: {username}
    password: {password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{address}/cloud_monitor?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=CONVERT_TO_NULL&autoReconnect=true&useSSL=false
    hikari:
      max-lifetime: 6000
      connection-timeout: 3000

prometheus:
  address: {address}
  addressVerification: {addressVerification}
  employ: true

http:
  maxTotal: 128
  defaultMaxPerRoute: 30
  connectTimeout: 5000
  connectionRequestTimeout: 5000
  socketTimeout: 10000
  staleConnectionCheckEnabled: true



