spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:/mappers/*

swagger:
  show: true

http:
  maxTotal: 128
  defaultMaxPerRoute: 30
  connectTimeout: 5000
  connectionRequestTimeout: 5000
  socketTimeout: 10000
  staleConnectionCheckEnabled: true

